version: "3.4"
services:
  logparser:
    container_name: logparser
    image: birdlex/cp-logparser
    stdin_open: true
    tty: true
    ports:
      - 6514:6514/udp
    depends_on:
      - redis
    restart: always
    volumes:
      - ./data/db:/app/db
      - ./data/log:/app/log
    environment:
      - REDIS_HOST=redis
  redis: #redis:6.2.13-alpine3.18
    container_name: logparser-redis
    #ports:
    #  - 6379:6379/tcp
    image: redis:6.2.13-alpine3.18
    restart: always
    volumes:
      - ./data/redis:/data
  nginx:
    image: birdlex/cp-logparser-nginx
    container_name: logparser-nginx
    depends_on:
      - logparser
    restart: always
    ports:
      - 443:443/tcp

